// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "market.goravel.dev/package/app/models"
)

// Package is an autogenerated mock type for the Package type
type Package struct {
	mock.Mock
}

// GetPackageByID provides a mock function with given fields: id
func (_m *Package) GetPackageByID(id string) (*models.Package, error) {
	ret := _m.Called(id)

	var r0 *models.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Package, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Package); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPackage creates a new instance of Package. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPackage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Package {
	mock := &Package{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
