// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	base "market.goravel.dev/proto/base"

	models "market.goravel.dev/package/app/models"
)

// Tag is an autogenerated mock type for the Tag type
type Tag struct {
	mock.Mock
}

// GetTags provides a mock function with given fields: packageID, name, pagination, total
func (_m *Tag) GetTags(packageID string, name string, pagination *base.Pagination, total *int64) ([]*models.Tag, error) {
	ret := _m.Called(packageID, name, pagination, total)

	var r0 []*models.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, *base.Pagination, *int64) ([]*models.Tag, error)); ok {
		return rf(packageID, name, pagination, total)
	}
	if rf, ok := ret.Get(0).(func(string, string, *base.Pagination, *int64) []*models.Tag); ok {
		r0 = rf(packageID, name, pagination, total)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, *base.Pagination, *int64) error); ok {
		r1 = rf(packageID, name, pagination, total)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTag creates a new instance of Tag. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTag(t interface {
	mock.TestingT
	Cleanup(func())
}) *Tag {
	mock := &Tag{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
