docker run -dit \
  -p $INPUT_PACKAGE_GRPC_PORT:$INPUT_PACKAGE_GRPC_PORT \
  -e APP_ENV=$INPUT_APP_ENV \
  -e APP_KEY=$INPUT_PACKAGE_APP_KEY \
  -e APP_DEBUG=true \
  -e GRPC_HOST=0.0.0.0 \
  -e GRPC_PORT=$INPUT_PACKAGE_GRPC_PORT \
  -e GRPC_USER_HOST=$INPUT_USER_GRPC_HOST \
  -e GRPC_USER_PORT=$INPUT_USER_GRPC_PORT \
  -e DB_HOST=$INPUT_DB_HOST \
  -e DB_PORT=$INPUT_DB_PORT \
  -e DB_DATABASE=$INPUT_PACKAGE_DB_DATABASE \
  -e DB_USERNAME=$INPUT_DB_USERNAME \
  -e DB_PASSWORD=$INPUT_DB_PASSWORD \
  -e REDIS_HOST=$INPUT_REDIS_HOST \
  -e REDIS_PORT=$INPUT_REDIS_PORT \
  --network $INPUT_APP_ENV \
  --network-alias goravel-market-$INPUT_APP_NAME \
  --name goravel-market-$INPUT_APP_ENV-$INPUT_APP_NAME \
  $INPUT_IMAGE