name: 'Deploy user'
description: 'Deploy the user service'

inputs:
  env:
    description: ''
    required: true
  image:
    description: ''
    required: true
  server_host:
    description: ''
    required: true
  server_username:
    description: ''
    required: true
  server_password:
    description: ''
    required: true
  server_port:
    description: ''
    required: true
  app_key:
    description: ''
    required: true
  http_port:
    description: ''
    required: true
  gateway_port:
    description: ''
    required: true
  grpc_user_host:
    description: ''
    required: true
  grpc_user_port:
    description: ''
    required: true

runs:
  using: "composite"
  steps:
    - name: Deploy gateway
      uses: appleboy/ssh-action@v1.0.0
      env:
        NAME: gateway
      with:
        host: ${{ inputs.server_host }}
        username: ${{ inputs.server_username }}
        password: ${{ inputs.server_password }}
        port: ${{ inputs.server_port }}
        envs: NAME
        script: |
          docker pull ${{ inputs.image }}
          if docker ps --format '{{.Names}}' | grep goravel-market-$NAME; then 
            docker stop goravel-market-$NAME && docker rm goravel-market-$NAME 
          fi
          docker run -dit \
            -p ${{ inputs.http_port }}:${{ inputs.http_port }} \
            -e APP_ENV=${{ inputs.env }} \
            -e APP_KEY=${{ inputs.app_key }} \
            -e APP_DEBUG=true \
            -e APP_HOST=0.0.0.0 \
            -e APP_PORT=${{ inputs.http_port }} \
            -e GRPC_USER_HOST=${{ inputs.grpc_user_host }} \
            -e GRPC_USER_PORT=${{ inputs.grpc_user_port }} \
            -e GATEWAY_HOST=0.0.0.0 \
            -e GATEWAY_PORT=${{ inputs.gateway_port }} \
            --network goravel-market \
            --network-alias $NAME \
            --name goravel-market-$NAME \
            ${{ inputs.image }}
