// Code generated by protoc-gen-go. DO NOT EDIT.
// source: package/package.proto

package _package

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	base "market.goravel.dev/proto/base"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Package struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Summary              string   `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Link                 string   `protobuf:"bytes,6,opt,name=link,proto3" json:"link,omitempty"`
	Version              string   `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	LastUpdatedAt        string   `protobuf:"bytes,8,opt,name=last_updated_at,json=lastUpdatedAt,proto3" json:"last_updated_at,omitempty"`
	CreatedAt            string   `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            string   `protobuf:"bytes,11,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Package) Reset()         { *m = Package{} }
func (m *Package) String() string { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()    {}
func (*Package) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c9118ab30eda21, []int{0}
}

func (m *Package) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Package.Unmarshal(m, b)
}
func (m *Package) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Package.Marshal(b, m, deterministic)
}
func (m *Package) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Package.Merge(m, src)
}
func (m *Package) XXX_Size() int {
	return xxx_messageInfo_Package.Size(m)
}
func (m *Package) XXX_DiscardUnknown() {
	xxx_messageInfo_Package.DiscardUnknown(m)
}

var xxx_messageInfo_Package proto.InternalMessageInfo

func (m *Package) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Package) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Package) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Package) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *Package) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Package) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *Package) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Package) GetLastUpdatedAt() string {
	if m != nil {
		return m.LastUpdatedAt
	}
	return ""
}

func (m *Package) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Package) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Package) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

type GetPackageRequest struct {
	// Auto-injected by the API Gateway.
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id                   string   `protobuf:"bytes,10,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPackageRequest) Reset()         { *m = GetPackageRequest{} }
func (m *GetPackageRequest) String() string { return proto.CompactTextString(m) }
func (*GetPackageRequest) ProtoMessage()    {}
func (*GetPackageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c9118ab30eda21, []int{1}
}

func (m *GetPackageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPackageRequest.Unmarshal(m, b)
}
func (m *GetPackageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPackageRequest.Marshal(b, m, deterministic)
}
func (m *GetPackageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPackageRequest.Merge(m, src)
}
func (m *GetPackageRequest) XXX_Size() int {
	return xxx_messageInfo_GetPackageRequest.Size(m)
}
func (m *GetPackageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPackageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPackageRequest proto.InternalMessageInfo

func (m *GetPackageRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetPackageRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPackageResponse struct {
	Status               *base.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Package              *Package     `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetPackageResponse) Reset()         { *m = GetPackageResponse{} }
func (m *GetPackageResponse) String() string { return proto.CompactTextString(m) }
func (*GetPackageResponse) ProtoMessage()    {}
func (*GetPackageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c9118ab30eda21, []int{2}
}

func (m *GetPackageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPackageResponse.Unmarshal(m, b)
}
func (m *GetPackageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPackageResponse.Marshal(b, m, deterministic)
}
func (m *GetPackageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPackageResponse.Merge(m, src)
}
func (m *GetPackageResponse) XXX_Size() int {
	return xxx_messageInfo_GetPackageResponse.Size(m)
}
func (m *GetPackageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPackageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPackageResponse proto.InternalMessageInfo

func (m *GetPackageResponse) GetStatus() *base.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetPackageResponse) GetPackage() *Package {
	if m != nil {
		return m.Package
	}
	return nil
}

func init() {
	proto.RegisterType((*Package)(nil), "package.Package")
	proto.RegisterType((*GetPackageRequest)(nil), "package.GetPackageRequest")
	proto.RegisterType((*GetPackageResponse)(nil), "package.GetPackageResponse")
}

func init() {
	proto.RegisterFile("package/package.proto", fileDescriptor_74c9118ab30eda21)
}

var fileDescriptor_74c9118ab30eda21 = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xcd, 0x8a, 0xd4, 0x40,
	0x10, 0x66, 0xe2, 0x3a, 0x71, 0x6a, 0x74, 0x57, 0x1b, 0x64, 0xdb, 0x51, 0x71, 0x08, 0x22, 0xe2,
	0x21, 0x81, 0xf1, 0xea, 0x65, 0xbd, 0x88, 0x37, 0x99, 0xc5, 0x8b, 0x97, 0xa1, 0x67, 0xba, 0x36,
	0x34, 0x93, 0xa4, 0x63, 0x57, 0x27, 0x28, 0xe2, 0xc5, 0x57, 0xf0, 0x59, 0x7c, 0x12, 0x5f, 0xc1,
	0x07, 0x91, 0xfe, 0xd3, 0x88, 0x7b, 0x49, 0xba, 0xbe, 0xbf, 0x74, 0xaa, 0x0a, 0xee, 0xf7, 0xe2,
	0x70, 0x14, 0x35, 0x56, 0xf1, 0x5d, 0xf6, 0x46, 0x5b, 0xcd, 0xf2, 0x58, 0xae, 0x1e, 0xd5, 0x5a,
	0xd7, 0x0d, 0x56, 0xa2, 0x57, 0x95, 0xe8, 0x3a, 0x6d, 0x85, 0x55, 0xba, 0xa3, 0x20, 0x5b, 0x9d,
	0xed, 0x05, 0x61, 0xe5, 0x1e, 0x01, 0x28, 0x7e, 0x64, 0x90, 0xbf, 0x0b, 0x56, 0x76, 0x0a, 0x99,
	0x92, 0x7c, 0xb6, 0x9e, 0x3d, 0x5f, 0x6c, 0x33, 0x25, 0xd9, 0x39, 0xe4, 0x03, 0xa1, 0xd9, 0x29,
	0xc9, 0x33, 0x0f, 0xce, 0x5d, 0xf9, 0x56, 0x32, 0x06, 0x27, 0x9d, 0x68, 0x91, 0xdf, 0xf0, 0xa8,
	0x3f, 0x33, 0x0e, 0x39, 0x0d, 0x6d, 0x2b, 0xcc, 0x67, 0x7e, 0xe2, 0xe1, 0x54, 0xb2, 0x35, 0x2c,
	0x25, 0xd2, 0xc1, 0xa8, 0xde, 0xdd, 0x84, 0xdf, 0xf4, 0xec, 0x14, 0x72, 0x79, 0x8d, 0xea, 0x8e,
	0x7c, 0x1e, 0xf2, 0xdc, 0xd9, 0xe5, 0x8d, 0x68, 0xc8, 0x39, 0xf2, 0x90, 0x17, 0x4b, 0xf6, 0x0c,
	0xce, 0x1a, 0x41, 0x76, 0x37, 0xf4, 0x52, 0x58, 0x94, 0x3b, 0x61, 0xf9, 0x2d, 0xaf, 0xb8, 0xe3,
	0xe0, 0xf7, 0x01, 0xbd, 0xb0, 0xec, 0x31, 0xc0, 0xc1, 0x60, 0x92, 0x2c, 0xbc, 0x64, 0x11, 0x91,
	0x40, 0x4f, 0x12, 0x20, 0xd0, 0xc3, 0xd4, 0x2d, 0xb1, 0xc1, 0x48, 0x2f, 0x03, 0x1d, 0x91, 0x0b,
	0x5b, 0xbc, 0x82, 0x7b, 0x6f, 0xd0, 0xc6, 0xce, 0x6d, 0xf1, 0xe3, 0x80, 0x64, 0xa7, 0x0d, 0x9b,
	0xfd, 0xd3, 0xb0, 0xd0, 0x59, 0x48, 0x9d, 0x2d, 0xae, 0x80, 0x4d, 0xdd, 0xd4, 0xeb, 0x8e, 0x90,
	0x3d, 0x85, 0x39, 0x59, 0x61, 0x07, 0xf2, 0xee, 0xe5, 0xe6, 0x76, 0xe9, 0x07, 0x75, 0xe9, 0xb1,
	0x6d, 0xe4, 0xd8, 0x0b, 0x48, 0xb3, 0xf6, 0x53, 0x59, 0x6e, 0xee, 0x96, 0x69, 0x15, 0x52, 0x60,
	0x12, 0x6c, 0x3e, 0xc1, 0x69, 0xc4, 0x2e, 0xd1, 0x8c, 0xea, 0x80, 0xec, 0x0a, 0xe0, 0xef, 0x97,
	0xd9, 0xea, 0x8f, 0xf5, 0xbf, 0x9f, 0x59, 0x3d, 0xbc, 0x96, 0x0b, 0x57, 0x2d, 0x9e, 0x7c, 0xfb,
	0xf9, 0xeb, 0x7b, 0xf6, 0x80, 0x9d, 0x57, 0xfb, 0x81, 0x54, 0x87, 0x44, 0x69, 0x1f, 0xa9, 0xfa,
	0xa2, 0xe4, 0xd7, 0xd7, 0xc5, 0x87, 0x75, 0x2b, 0xcc, 0x11, 0x6d, 0x59, 0x6b, 0x23, 0x46, 0x6c,
	0x4a, 0x89, 0x63, 0xe5, 0x77, 0x2e, 0x29, 0xf7, 0x73, 0x5f, 0xbe, 0xfc, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0xdf, 0x86, 0x7a, 0xa9, 0xd3, 0x02, 0x00, 0x00,
}
