// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// User is an autogenerated mock type for the User type
type User struct {
	mock.Mock
}

type User_Expecter struct {
	mock *mock.Mock
}

func (_m *User) EXPECT() *User_Expecter {
	return &User_Expecter{mock: &_m.Mock}
}

// IsEmailExist provides a mock function with given fields: email
func (_m *User) IsEmailExist(email string) (bool, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for IsEmailExist")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// User_IsEmailExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEmailExist'
type User_IsEmailExist_Call struct {
	*mock.Call
}

// IsEmailExist is a helper method to define mock.On call
//   - email string
func (_e *User_Expecter) IsEmailExist(email interface{}) *User_IsEmailExist_Call {
	return &User_IsEmailExist_Call{Call: _e.mock.On("IsEmailExist", email)}
}

func (_c *User_IsEmailExist_Call) Run(run func(email string)) *User_IsEmailExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *User_IsEmailExist_Call) Return(_a0 bool, _a1 error) *User_IsEmailExist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *User_IsEmailExist_Call) RunAndReturn(run func(string) (bool, error)) *User_IsEmailExist_Call {
	_c.Call.Return(run)
	return _c
}

// NewUser creates a new instance of User. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *User {
	mock := &User{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
