// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TagInterface is an autogenerated mock type for the TagInterface type
type TagInterface struct {
	mock.Mock
}

// NewTagInterface creates a new instance of TagInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTagInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TagInterface {
	mock := &TagInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
