staging:
  gateway:
    http:
      port: 4000
    gateway:
      port: 4001
  user:
    grpc:
      host: user
      port: 4011
    db:
      host: postgres
      port: 5432
      database: user
    redis:
      host: redis
      port: 6379
  package:
    grpc:
      host: package
      port: 4021
