version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: goravel
      POSTGRES_USER: goravel
      POSTGRES_PASSWORD: goravel
