name: Build Docker Image

on:
  create:
    tags:
      - '*'
jobs:
  gateway:
    if: startsWith(github.ref, 'refs/tags/gateway-')
    strategy:
      matrix:
        go:
          - "1.21"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/go
    steps:
    - uses: actions/checkout@v4
    - name: Set up environment
      id: env_setup
      run: |
        echo "REPO_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

    # This step can be moved to the deploy.yml file in the future
    - name: Update remote server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEVELOPMENT_SERVER_HOST }}
        username: ${{ secrets.DEVELOPMENT_SERVER_USERNAME }}
        password: ${{ secrets.DEVELOPMENT_SERVER_PASSWORD }}
        port: ${{ secrets.DEVELOPMENT_SERVER_PORT }}
        envs: REPO_TAG
        script: |
          docker pull ${{ secrets.ALIYUN_ACR_REGISTRY }}:$REPO_TAG
          if docker ps --format '{{.Names}}' | grep goravel-market-gateway; then 
            docker stop goravel-market-gateway && docker rm goravel-market-gateway 
          fi
          docker run -dit -p 4000:4000 -e APP_PORT=4000 -e GRPC_USER_PORT=4010 -e GATEWAY_PORT=4001 -e APP_ENV=development -e APP_KEY=${{ secrets.GATEWAY_APP_KEY }} -e APP_DEBUG=true --network goravel-market --network-alias gateway --name goravel-market-gateway ${{ secrets.ALIYUN_ACR_REGISTRY }}:$REPO_TAG
