name: Build Docker Image

on:
  create:
    tags:
      - '*'
jobs:
  gateway:
    if: startsWith(github.ref, 'refs/tags/gateway-')
    strategy:
      matrix:
        go:
          - "1.21"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up environment
      id: env_setup
      run: |
        echo "REPO_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

    # This step can be moved to the deploy.yml file in the future
    - name: Load deploy configuration
      uses: actions-tools/yaml-outputs@v2
      id: load_config
      with:
        file-path: ./config/deploy.yml

    - name: Update remote server
      uses: appleboy/ssh-action@v1.0.3
      env:
        HTTP_PORT: ${{ steps.load_config.outputs.development__gateway__http_port }}
        GATEWAY_PORT: ${{ steps.load_config.outputs.development__gateway__gateway_port }}
        USER_GRPC_PORT: ${{ steps.load_config.outputs.development__user__grpc_port }}
      with:
        host: ${{ secrets.DEVELOPMENT_SERVER_HOST }}
        username: ${{ secrets.DEVELOPMENT_SERVER_USERNAME }}
        password: ${{ secrets.DEVELOPMENT_SERVER_PASSWORD }}
        port: ${{ secrets.DEVELOPMENT_SERVER_PORT }}
        envs: REPO_TAG,HTTP_PORT,GATEWAY_PORT,USER_GRPC_PORT
        script: |
          echo "HTTP_PORT=$HTTP_PORT"
          echo "GATEWAY_PORT=$GATEWAY_PORT"
          echo "USER_GRPC_PORT=$USER_GRPC_PORT"
          
          docker pull ${{ secrets.ALIYUN_ACR_REGISTRY }}:$REPO_TAG
          if docker ps --format '{{.Names}}' | grep goravel-market-gateway; then 
            docker stop goravel-market-gateway && docker rm goravel-market-gateway 
          fi
          docker run -dit -p $HTTP_PORT:$HTTP_PORT -e APP_PORT=$HTTP_PORT -e GRPC_USER_PORT=$USER_GRPC_PORT -e GATEWAY_PORT=$GATEWAY_PORT -e APP_ENV=development -e APP_KEY=${{ secrets.GATEWAY_APP_KEY }} -e APP_DEBUG=true --network goravel-market --network-alias gateway --name goravel-market-gateway ${{ secrets.ALIYUN_ACR_REGISTRY }}:$REPO_TAG
