name: Build Docker Image

on:
  create:
    tags:
      - '*'
jobs:
  gateway:
    if: startsWith(github.ref, 'refs/tags/gateway-')
    strategy:
      matrix:
        go:
          - "1.21"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/go
    steps:
    - uses: actions/checkout@v4
    - name: Set up environment
      id: env_setup
      run: |
        echo "REPO_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

    # This step can be moved to the deploy.yml file in the future
    - name: Update remote server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEVELOPMENT_SERVER_HOST }}
        username: ${{ secrets.DEVELOPMENT_SERVER_USERNAME }}
        password: ${{ secrets.DEVELOPMENT_SERVER_PASSWORD }}
        port: ${{ secrets.DEVELOPMENT_SERVER_PORT }}
        envs: REPO_TAG
        script: |
          echo "$IMAGE"
          docker pull ${{ secrets.ALIYUN_ACR_REGISTRY }}:$REPO_TAG
