name: Deploy

jobs:
  deploy:
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Load deploy configuration
      uses: actions-tools/yaml-outputs@v2
      id: load_config
      with:
        export-env-variables: false
        file-path: ./config/deploy.yml

    # ************************** IMPORTANT **************************
    # Add the variables that needed by microservices here, the prefix must be INPUT_, it's a rule of the action.
    # You only need to modify this step when you add a new microservice.
    - name: Set deploy environment variables
      run: |
        echo "INPUT_APP_ENV=${{ inputs.env }}" >> $GITHUB_ENV
        echo "INPUT_APP_NAME=${inputs.tag%-*}" >> $GITHUB_ENV
        echo "INPUT_IMAGE=${{ secrets.ALIYUN_ACR_REGISTRY }}:${{ inputs.tag }}" >> $GITHUB_ENV
        echo "INPUT_DEPLOY=$(cat ./src/go/$INPUT_APP_NAME/deploy.sh | base64 | tr -d '\n')" >> $GITHUB_ENV
        
        echo "INPUT_GATEWAY_APP_KEY=${{ secrets.GATEWAY_APP_KEY }}" >> $GITHUB_ENV

        echo "INPUT_HTTP_PORT=${{ steps.load_config.outputs.staging__gateway__http__port }}" >> $GITHUB_ENV
        echo "INPUT_GATEWAY_PORT=${{ steps.load_config.outputs.staging__gateway__gateway__port }}" >> $GITHUB_ENV
        echo "INPUT_GRPC_USER_HOST=${{ steps.load_config.outputs.staging__user__grpc__HOST }}" >> $GITHUB_ENV
        echo "INPUT_GRPC_USER_PORT=${{ steps.load_config.outputs.staging__user__grpc__port }}" >> $GITHUB_ENV

    - name: Login to ACR
      uses: aliyun/acr-login@v1
      with:
        username: ${{ secrets.ALIYUN_ACR_USERNAME }}
        password: ${{ secrets.ALIYUN_ACR_PASSWORD }}
        region-id: ${{ secrets.ALIYUN_ACR_REGION_ID }}
        login-server: ${{ secrets.ALIYUN_ACR_LOGIN_SERVER }}

    - name: Deploy gateway
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        allenvs: true
        script: |
          docker pull $INPUT_IMAGE
          if docker ps --format '{{.Names}}' | grep goravel-market-$INPUT_APP_NAME; then 
            docker stop goravel-market-$INPUT_APP_NAME && docker rm goravel-market-$INPUT_APP_NAME 
          fi
          echo $INPUT_DEPLOY | base64 -d | bash

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'The environment'
        required: true
        type: choice
        options:
          - staging
          - production
      tag:
        description: 'The repository tag'
        required: true
        type: string
  workflow_call:
    inputs:
      env:
        description: 'The environment: staging or production'
        required: true
        type: string
      tag:
        description: 'The repository tag'
        required: true
        type: string
