name: Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'The environment'
        required: true
        type: choice
        options:
          - staging
          - production
      tag:
        description: 'The repository tag'
        required: true
        type: string
  workflow_call:
    inputs:
      env:
        description: 'The environment: staging or production'
        required: true
        type: string
      tag:
        description: 'The repository tag'
        required: true
        type: string

jobs:
  deploy:
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to ACR
      uses: aliyun/acr-login@v1
      with:
        username: ${{ secrets.ALIYUN_ACR_USERNAME }}
        password: ${{ secrets.ALIYUN_ACR_PASSWORD }}
        region-id: ${{ secrets.ALIYUN_ACR_REGION_ID }}
        login-server: ${{ secrets.ALIYUN_ACR_LOGIN_SERVER }}

    - name: Load deploy configuration
      uses: actions-tools/yaml-outputs@v2
      id: load_config
      with:
        file-path: ./config/deploy.yml

    - name: Deploy gateway
      if: startsWith(inputs.tag, 'gateway-')
      uses: ./.github/deploy/gateway
      with:
        env: ${{ inputs.env }}
        image: ${{ secrets.ALIYUN_ACR_REGISTRY }}:${{ inputs.tag }}
        server_host: ${{ secrets.SERVER_HOST }}
        server_username: ${{ secrets.SERVER_USERNAME }}
        server_password: ${{ secrets.SERVER_PASSWORD }}
        server_port: ${{ secrets.SERVER_PORT }}
        app_key: ${{ secrets.GATEWAY_APP_KEY }}
        http_port: ${{ steps.load_config.outputs.staging__gateway__http__port }}
        gateway_port: ${{ steps.load_config.outputs.staging__gateway__gateway__port }}
        grpc_user_host: ${{ steps.load_config.outputs.staging__user__grpc__HOST }}
        grpc_user_port: ${{ steps.load_config.outputs.staging__user__grpc__port }}
