name: Docker Image CI

on:
  create:
    tags:
      - '*'
jobs:
  gateway:
    if: startsWith(github.ref, 'refs/tags/gateway-')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/go/gateway
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t ${GITHUB_REF##*/} .
